### PR TITLE
Refactor bootstrap process; Increase apt package idemopotency; Add support for MinIO

### PR DESCRIPTION
**Pull request by codrcodz**
This PR adds flags to the bootstrap script to make some of it's behaviors more configurable. PR also removes all "lastest" values from tasks that reference the anisble apt module and changes those to "present" to ensure system dependencies remain consistent. This increases stability and is an incremental step in turning this role into one that can be used for production.

### CODE REVIEW

**Review by dingus9 — APPROVED** [review]
LGTM: make it so, I tested this yesterday before the PR

**Comment by codrcodz** [comment]
So, this never got merged, but I added another commit.

**Review by dingus9 — APPROVED** [review]
make it so... as long as a course is laid in

**Comment by ragingpastry** [comment]
Worked on my machine. Merging

**Pull request merged**
